name: 🐛 Bug Report
description: Report a bug or regression
labels: [bug]
body:
  - type: input
    id: affected-version
    attributes:
      label: Affected Version
      description: What version of Loom Spinner does this affect?
      placeholder: e.g. 3.0.0
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what happened
      placeholder: Steps to reproduce...
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
